/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kargosistemi;

/**
 *
 * @author hatice
 */
public class KargoEkleme extends javax.swing.JFrame {
    Musteri mus;
    int kID;
    Kaydedici kaydedici = new Kaydedici();
    /**
     * Creates new form KargoEkleme
     */
    public KargoEkleme(){
        initComponents();
    }
    public KargoEkleme(Musteri mus) {
        this.mus = mus;
        initComponents();
        jPanelUrunBilgileri.setVisible(true);
        jPanelUrunKargoBilgileri.setVisible(false);
        jPanelAcikEksiltme.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jPanelUrunBilgileri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUrunTipi = new javax.swing.JTextField();
        jTextFieldAgirlik = new javax.swing.JTextField();
        jTextFieldEbatX = new javax.swing.JTextField();
        jTextFieldAdet = new javax.swing.JTextField();
        jButtonUrunKaydet = new javax.swing.JButton();
        jTextFieldEbatY = new javax.swing.JTextField();
        jLabelUrunHata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelUrunKargoBilgileri = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelUrunTipi = new javax.swing.JLabel();
        jLabelAgirlik = new javax.swing.JLabel();
        jLabelEbat = new javax.swing.JLabel();
        jLabelAdet = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelUrunID = new javax.swing.JLabel();
        jLabelKUrunID = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelKToplamAgirlik = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelKToplamEbat = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelKargoID = new javax.swing.JLabel();
        jButtonAcikEksiltmeBaslat = new javax.swing.JButton();
        jPanelAcikEksiltme = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldUcret = new javax.swing.JTextField();
        jTextFieldTAAdres = new javax.swing.JTextField();
        jTextFieldTEAdres = new javax.swing.JTextField();
        jTextFieldTarihBaslangic = new javax.swing.JTextField();
        jTextFieldTarihBitis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldAEBITISTARIH = new javax.swing.JTextField();
        jLabelAEHata = new javax.swing.JLabel();

        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(421, 390));

        jLabel2.setText("Ürün Tipi :");

        jLabel3.setText("Ağırlık : ");

        jLabel4.setText("Ebat :");

        jLabel5.setText("Adet :");

        jTextFieldAgirlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgirlikActionPerformed(evt);
            }
        });

        jButtonUrunKaydet.setText("Kaydet");
        jButtonUrunKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUrunKaydetActionPerformed(evt);
            }
        });

        jLabel1.setText("Ürün Bilgilerini Giriniz");

        javax.swing.GroupLayout jPanelUrunBilgileriLayout = new javax.swing.GroupLayout(jPanelUrunBilgileri);
        jPanelUrunBilgileri.setLayout(jPanelUrunBilgileriLayout);
        jPanelUrunBilgileriLayout.setHorizontalGroup(
            jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUrunBilgileriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUrunBilgileriLayout.createSequentialGroup()
                        .addGroup(jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUrunTipi, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(jTextFieldAgirlik)
                            .addComponent(jTextFieldAdet)
                            .addGroup(jPanelUrunBilgileriLayout.createSequentialGroup()
                                .addComponent(jTextFieldEbatX, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEbatY, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelUrunBilgileriLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButtonUrunKaydet))
                    .addGroup(jPanelUrunBilgileriLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelUrunHata, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanelUrunBilgileriLayout.setVerticalGroup(
            jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUrunBilgileriLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUrunHata, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldUrunTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAgirlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEbatX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEbatY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUrunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAdet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButtonUrunKaydet))
        );

        jLabel6.setText("Ürün Bilgileri");

        jLabel7.setText("Ürün Tipi :");

        jLabel8.setText("Ağırlık :");

        jLabel9.setText("Ebat : ");

        jLabel10.setText("Adet : ");

        jLabel11.setText("Kargo Bilgileri ");

        jLabel12.setText("Ürün ID :");

        jLabel13.setText("Ürün ID :");

        jLabel14.setText("Toplam Ağırlık :");

        jLabel16.setText("Toplam Ebat :");

        jLabel17.setText("Kargo ID :");

        jButtonAcikEksiltmeBaslat.setText("Açık Eksiltme");
        jButtonAcikEksiltmeBaslat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcikEksiltmeBaslatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUrunKargoBilgileriLayout = new javax.swing.GroupLayout(jPanelUrunKargoBilgileri);
        jPanelUrunKargoBilgileri.setLayout(jPanelUrunKargoBilgileriLayout);
        jPanelUrunKargoBilgileriLayout.setHorizontalGroup(
            jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                        .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUrunTipi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAgirlik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEbat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAdet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelUrunID, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))))
                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelKUrunID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelKToplamAgirlik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelKToplamEbat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11)
                                    .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelKargoID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 61, Short.MAX_VALUE))))
                    .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAcikEksiltmeBaslat, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelUrunKargoBilgileriLayout.setVerticalGroup(
            jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                        .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabelUrunTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabelKUrunID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabelAgirlik, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabelKToplamAgirlik, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabelEbat, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelKToplamEbat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabelAdet, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabelKargoID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                        .addGroup(jPanelUrunKargoBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelUrunID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))
                    .addGroup(jPanelUrunKargoBilgileriLayout.createSequentialGroup()
                        .addComponent(jButtonAcikEksiltmeBaslat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel18.setText("Açık Eksiltme Bilgilerini Giriniz");

        jLabel19.setText("Ücret : ");

        jLabel15.setText("Teslim Alınacak Adres :");

        jLabel20.setText("Teslim Edilecek Adres :");

        jLabel21.setText("Tarih Başlangıç :");

        jLabel23.setText("Tarih Bitiş :");

        jTextFieldTAAdres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTAAdresActionPerformed(evt);
            }
        });

        jButton1.setText("Açık Eksiltme Başlat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Açık Eksiltme Bitiş Tarihi : ");

        javax.swing.GroupLayout jPanelAcikEksiltmeLayout = new javax.swing.GroupLayout(jPanelAcikEksiltme);
        jPanelAcikEksiltme.setLayout(jPanelAcikEksiltmeLayout);
        jPanelAcikEksiltmeLayout.setHorizontalGroup(
            jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcikEksiltmeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAcikEksiltmeLayout.createSequentialGroup()
                        .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAcikEksiltmeLayout.createSequentialGroup()
                        .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAcikEksiltmeLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAcikEksiltmeLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAcikEksiltmeLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(36, 36, 36)
                                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTEAdres)
                                    .addComponent(jTextFieldTAAdres)
                                    .addComponent(jTextFieldTarihBaslangic)
                                    .addComponent(jTextFieldTarihBitis)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAcikEksiltmeLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabelAEHata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(36, 36, 36))))
            .addGroup(jPanelAcikEksiltmeLayout.createSequentialGroup()
                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAcikEksiltmeLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAcikEksiltmeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAEBITISTARIH)))
                .addGap(36, 36, 36))
        );
        jPanelAcikEksiltmeLayout.setVerticalGroup(
            jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcikEksiltmeLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(8, 8, 8)
                .addComponent(jLabelAEHata, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldUcret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldTAAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldTEAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldTarihBaslangic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldTarihBitis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAcikEksiltmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jTextFieldAEBITISTARIH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUrunKargoBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAcikEksiltme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelUrunBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUrunBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelUrunKargoBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAcikEksiltme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAgirlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgirlikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgirlikActionPerformed

    private void jButtonUrunKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUrunKaydetActionPerformed

        String urunTipi;
        double agirlik;
        int adet,ebatX,ebatY;
        
        urunTipi = jTextFieldUrunTipi.getText();
        if(urunTipi.length() > 0 && jTextFieldAgirlik.getText().length() >0 && jTextFieldEbatX.getText().length() >0 && jTextFieldEbatY.getText().length() > 0 && jTextFieldAdet.getText().length() > 0){
            agirlik = new Double(jTextFieldAgirlik.getText());
            ebatX = new Integer(jTextFieldEbatX.getText());
            ebatY = new Integer(jTextFieldEbatY.getText());
            adet = new Integer(jTextFieldAdet.getText());

            Urun yeniUrun = new Urun(mus.mID, urunTipi, agirlik, ebatX, ebatY, adet);
            kaydedici.urunBilgisiGir(yeniUrun);

            int toplamEbat=0;
            double toplamAgirlik = 0.0 ;
            for(int i=0; i<adet; i++){
                toplamEbat += ebatY;
                toplamAgirlik += agirlik;
            }
            
            int ID = (int)kaydedici.sonuncuGetir(yeniUrun);

            Kargo yeniKargo = new Kargo(mus.mID, ID, toplamAgirlik, ebatX, toplamEbat);
            kaydedici.kargiBilgileriGir(yeniKargo);

            jPanelUrunBilgileri.setVisible(false);
            jPanelUrunKargoBilgileri.setVisible(true);
            jPanelAcikEksiltme.setVisible(false);

            jLabelUrunID.setText(Integer.toString(ID));
            jLabelAdet.setText(Integer.toString(adet));
            jLabelAgirlik.setText(String.valueOf(agirlik));
            jLabelUrunTipi.setText(urunTipi);
            jLabelEbat.setText(Integer.toString(ebatX)+" - "+Integer.toString(ebatY));
 
            kID = kaydedici.sonuncuGetir(yeniKargo);
            jLabelKToplamEbat.setText(Integer.toString(ebatX)+" - "+Integer.toString(toplamEbat));
            jLabelKUrunID.setText(Integer.toString(ID));
            jLabelKToplamAgirlik.setText(String.valueOf(toplamAgirlik));
            jLabelKargoID.setText(Integer.toString(kID));
        }
        else{
            jLabelUrunHata.setText("Lütfen ürün Bilgilerini eksiksiz doldurun!");
        }
    }//GEN-LAST:event_jButtonUrunKaydetActionPerformed

    private void jTextFieldTAAdresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTAAdresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTAAdresActionPerformed

    private void jButtonAcikEksiltmeBaslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcikEksiltmeBaslatActionPerformed
        jPanelUrunBilgileri.setVisible(false);
        jPanelUrunKargoBilgileri.setVisible(false);
        jPanelAcikEksiltme.setVisible(true);
    }//GEN-LAST:event_jButtonAcikEksiltmeBaslatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ucret;
        String teslimAlinacakAdres, teslimEdilecekAdres, tarihBaslangic, tarihBitis, aeBitisTarih;
        
        teslimAlinacakAdres = jTextFieldTAAdres.getText();
        teslimEdilecekAdres = jTextFieldTEAdres.getText();
        tarihBaslangic = jTextFieldTarihBaslangic.getText();
        tarihBitis = jTextFieldTarihBitis.getText();
        aeBitisTarih = jTextFieldAEBITISTARIH.getText();
        if(teslimAlinacakAdres.length() > 0 && teslimEdilecekAdres.length() > 0 && tarihBaslangic.length() > 0 && tarihBitis.length() > 0 && aeBitisTarih.length() > 0 && jTextFieldUcret.getText().length() > 0){
            ucret = new Integer(jTextFieldUcret.getText());

            AcikEksiltme yeniAcikEksiltme = new AcikEksiltme(mus.mID, kID, ucret, teslimAlinacakAdres, teslimEdilecekAdres, tarihBaslangic, tarihBitis, aeBitisTarih);
            kaydedici.acikEksiltmeBaslat(yeniAcikEksiltme);

            this.setVisible(false);
        }
        else{
            jLabelAEHata.setText("Boş Alanları Doldurunuz!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KargoEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KargoEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KargoEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KargoEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KargoEkleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAcikEksiltmeBaslat;
    private javax.swing.JButton jButtonUrunKaydet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAEHata;
    private javax.swing.JLabel jLabelAdet;
    private javax.swing.JLabel jLabelAgirlik;
    private javax.swing.JLabel jLabelEbat;
    private javax.swing.JLabel jLabelKToplamAgirlik;
    private javax.swing.JLabel jLabelKToplamEbat;
    private javax.swing.JLabel jLabelKUrunID;
    private javax.swing.JLabel jLabelKargoID;
    private javax.swing.JLabel jLabelUrunHata;
    private javax.swing.JLabel jLabelUrunID;
    private javax.swing.JLabel jLabelUrunTipi;
    private javax.swing.JPanel jPanelAcikEksiltme;
    private javax.swing.JPanel jPanelUrunBilgileri;
    private javax.swing.JPanel jPanelUrunKargoBilgileri;
    private javax.swing.JTextField jTextFieldAEBITISTARIH;
    private javax.swing.JTextField jTextFieldAdet;
    private javax.swing.JTextField jTextFieldAgirlik;
    private javax.swing.JTextField jTextFieldEbatX;
    private javax.swing.JTextField jTextFieldEbatY;
    private javax.swing.JTextField jTextFieldTAAdres;
    private javax.swing.JTextField jTextFieldTEAdres;
    private javax.swing.JTextField jTextFieldTarihBaslangic;
    private javax.swing.JTextField jTextFieldTarihBitis;
    private javax.swing.JTextField jTextFieldUcret;
    private javax.swing.JTextField jTextFieldUrunTipi;
    // End of variables declaration//GEN-END:variables
}
