/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kargosistemi;
/**
 *
 * @author hatice
 */
public class sistemAnasayfa extends javax.swing.JFrame {

    boolean musteriMi;
    
    public sistemAnasayfa() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMusteriUye = new javax.swing.JButton();
        jButtonTasiyiciUye = new javax.swing.JButton();
        jButtonMGiris = new javax.swing.JButton();
        jButtonTGiris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMusteriUye.setText("Müşteri Üye Ol");
        jButtonMusteriUye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMusteriUyeActionPerformed(evt);
            }
        });

        jButtonTasiyiciUye.setText("Taşıyıcı Üye Ol");
        jButtonTasiyiciUye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTasiyiciUyeActionPerformed(evt);
            }
        });

        jButtonMGiris.setText("Müşteri Giriş Yap");
        jButtonMGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMGirisActionPerformed(evt);
            }
        });

        jButtonTGiris.setText("Taşıyıcı Giriş Yap");
        jButtonTGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMGiris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMusteriUye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTasiyiciUye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTGiris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMusteriUye)
                    .addComponent(jButtonTasiyiciUye))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMGiris)
                    .addComponent(jButtonTGiris))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMusteriUyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMusteriUyeActionPerformed
        musteriKaydet musteriKaydol = new musteriKaydet();
        musteriKaydol.setVisible(true);
    }//GEN-LAST:event_jButtonMusteriUyeActionPerformed

    private void jButtonTasiyiciUyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTasiyiciUyeActionPerformed
        tasiyiciKaydet tasiyiciKaydol = new tasiyiciKaydet();
        tasiyiciKaydol.setVisible(true);
    }//GEN-LAST:event_jButtonTasiyiciUyeActionPerformed

    private void jButtonMGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMGirisActionPerformed
        musteriMi = true;
        girisYap mGiris = new girisYap(musteriMi);
        mGiris.setVisible(true);
    }//GEN-LAST:event_jButtonMGirisActionPerformed

    private void jButtonTGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTGirisActionPerformed
        musteriMi = false;
        girisYap tGiris = new girisYap(musteriMi);
        tGiris.setVisible(true);
    }//GEN-LAST:event_jButtonTGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistemAnasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistemAnasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistemAnasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistemAnasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistemAnasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMGiris;
    private javax.swing.JButton jButtonMusteriUye;
    private javax.swing.JButton jButtonTGiris;
    private javax.swing.JButton jButtonTasiyiciUye;
    // End of variables declaration//GEN-END:variables
}
