/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kargosistemi;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hatice
 */
public class TGirisSonrasi extends javax.swing.JFrame {
    Tasiyici tas;
    int kackez;
    int aeID;
    Kaydedici kaydedici = new Kaydedici();
    /**
     * Creates new form TGirisSonrasi
     */
    public TGirisSonrasi() {
        initComponents();
        jTable1.setVisible(false);
    }

    public TGirisSonrasi(Tasiyici tas){
        this.tas = tas;
        initComponents();
        jPanelTeklifVerme.setVisible(false);
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                kackez++;
                if(kackez%2 == 0){
                    jPanelTeklifVerme.setVisible(true);
                    
                    if(jTable1.getSelectedRow() < 0) 
                        jTable1.setRowSelectionInterval(0, 0);
                    aeID = (int)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                    
                    Teklifler teklifler = new Teklifler();
                    ResultSet rs = kaydedici.teklifleriGoster(teklifler, aeID);
                    int kacsutun=0;
                    try {
                        kacsutun = rs.getMetaData().getColumnCount(); //veritabanında kaç tane sütün olduğunu söylüyor.
                        DefaultTableModel model = (DefaultTableModel) jTableUcretler.getModel();//veri ekleyeceğimiz ortamı oluşturduk.
                        model.setRowCount(0);//butona her tıklanıldığında aynı şeyi eklememesi için tablo içeriğini sıfırlar.
                        
                        while(rs.next()){
                            Object[] row = new Object[kacsutun];
                            for(int i=0;i<kacsutun;i++){
                                row[i] = rs.getObject(i+1);
                            }
                            model.addRow(row);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(TGirisSonrasi.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelTeklifVerme = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTeklif = new javax.swing.JTextField();
        jButtonTeklifVerme = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUcretler = new javax.swing.JTable();
        jLabelTeklifHata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(995, 520));

        jButton1.setText("Açık Eksiltmeleri Listele");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AE No", "Ücret", "Teslim Alınacak Adres", "Teslim Edilecek Adres", "Teslim Başlama Tarihi", "Teslim Bitirme Tarihi", "Açık Eksiltme Süresi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Teklif Verme");

        jLabel2.setText("Teklifinizi Giriniz :");

        jButtonTeklifVerme.setText("Teklif Ver");
        jButtonTeklifVerme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeklifVermeActionPerformed(evt);
            }
        });

        jTableUcretler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Ücretler"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableUcretler);

        javax.swing.GroupLayout jPanelTeklifVermeLayout = new javax.swing.GroupLayout(jPanelTeklifVerme);
        jPanelTeklifVerme.setLayout(jPanelTeklifVermeLayout);
        jPanelTeklifVermeLayout.setHorizontalGroup(
            jPanelTeklifVermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeklifVermeLayout.createSequentialGroup()
                .addGroup(jPanelTeklifVermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTeklifVermeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonTeklifVerme, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTeklifVermeLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelTeklifVermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTeklifHata, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelTeklifVermeLayout.createSequentialGroup()
                                .addGroup(jPanelTeklifVermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTeklif, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTeklifVermeLayout.setVerticalGroup(
            jPanelTeklifVermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeklifVermeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabelTeklifHata, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeklifVermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTeklif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButtonTeklifVerme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTeklifVermeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jPanelTeklifVerme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelTeklifVerme, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTable1.setVisible(true);
        kackez = 0;
        ResultSet rs = kaydedici.acikEksiltmeleriGoster(tas);
        int kacsutun=0;
        try {
            kacsutun = rs.getMetaData().getColumnCount(); //veritabanında kaç tane sütün olduğunu söylüyor.
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();//veri ekleyeceğimiz ortamı oluşturduk.
            model.setRowCount(0);//butona her tıklanıldığında aynı şeyi eklememesi için tablo içeriğini sıfırlar.
            
            while(rs.next()){
                Object[] row = new Object[kacsutun];
                for(int i=0;i<kacsutun;i++){
                    row[i] = rs.getObject(i+1);
                }
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TGirisSonrasi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonTeklifVermeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeklifVermeActionPerformed
        double teklif;
        
        if(jTextFieldTeklif.getText().length() > 0){
            teklif = new Double(jTextFieldTeklif.getText());
            Teklifler yeniTeklif = new Teklifler(aeID, tas.tID, teklif);

            kaydedici.teklifVer(yeniTeklif);
        }
        else{
            jLabelTeklifHata.setText("Teklif Boş Girilemez!");
        }
    }//GEN-LAST:event_jButtonTeklifVermeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TGirisSonrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TGirisSonrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TGirisSonrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TGirisSonrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TGirisSonrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonTeklifVerme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTeklifHata;
    private javax.swing.JPanel jPanelTeklifVerme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableUcretler;
    private javax.swing.JTextField jTextFieldTeklif;
    // End of variables declaration//GEN-END:variables
}
